### ISSUE TITLE
Optimize use of stdout and stderr streams for logging

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/gedi-subsetter#56]
Currently, when a job fails the DPS captures the contents of the _stderr and displays that on the job management UI for easier debugging for the user. 

In case of the gedi subsetting algorithm this includes a lot of information that is causing our backend elasticsearch to slow down while serving up large amounts of text for users faceting on the job management UI. 

Example string from stderr of a failed job that could be piped to somewhere else. 
```
Connecting to daac.ornl.gov (daac.ornl.gov)|160.91.19.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74344526 (71M) [image/tiff]
Saving to: ‘input/boreal_agb_202302061675657080_0921.tif’

     0K .......... .......... .......... .......... ..........  0%  167K 7m15s
    50K .......... .......... .......... .......... ..........  0%  224K 6m19s
   100K .......... .......... .......... .......... ..........  0%  224K 6m0s
   150K .......... .......... .......... .......... ..........  0%  336K 5m24s
   200K .......... .......... .......... .......... ..........  0%  336K 5m2s
   250K .......... .......... .......... .......... ..........  0%  264K 4m57s
   300K .......... .......... .......... .......... ..........  0%  459K 4m37s
   350K .......... .......... .......... .......... ..........  0%  335K 4m29s
   400K .......... .......... .......... .......... ..........  0%  266K 4m29s
   450K .......... .......... .......... .......... ..........  0%  456K 4m18s
   500K .......... .......... .......... .......... ..........  0%  336K 4m14s
   550K .......... .......... .......... .......... ..........  0%  670K 4m1s
   600K .......... .......... .......... .......... ..........  0%  442K 3m55s
   650K .......... .......... .......... .......... ..........  0%  454K 3m50s
   700K .......... .......... .......... .......... ..........  1%  672K 3m41s
   750K .......... .......... .......... .......... ..........  1%  443K 3m37s
   800K .......... .......... .......... .......... ..........  1%  455K 3m34s
   850K .......... .......... .......... .......... ..........  1%  670K 3m28s
```

On the DPS side, we are working on reducing the no. of lines captured for display on the UI. 
https://github.com/MAAP-Project/Community/issues/879

**Comment by chuckwondo** [comment]
@sujen1412, I'm adding details here based on the Slack conversation we had a while back.

Per our convo, you indicated:

> Triage should automatically copy all *.log files in $PWD

Therefore, I'm going to implement the following logic for this issue (summarized from our Slack convo as well):

- Write logging output to a log file in `$PWD` (rather than to `stderr`, which is the crux of the problem)
- If the main algorithm code succeeds, the run script (which called the algo code) will copy the log file to the `${PWD}/output` directory so the user can see the log file, along with any other output produced
- If the algorithm code fails, the run script will exit before it can copy the log file to the output dir, so then it gets copied to the triaged directory automatically because the log file would remain in `$PWD`

Does that sound good?

**Comment by sujen1412** [comment]
Sounds good.
